name: Haskell CI

on:
  push:
    branches: [ "test-branch" ]
  pull_request:
    branches: [ "test-branch" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '9.6.2'
        cabal-version: '2.2'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
      working-directory: ./Lab2

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
      working-directory: ./Lab2

    - name: Run tests
      run: cabal test all
      working-directory: ./Lab2
